name = "lustre_ssg"
version = "0.8.1"
description = "A simple static site generator for Lustre projects."

licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "ssg" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = ">= 0.34.0"
jot = "1.0.1"
lustre = ">= 4.3.5 and < 5.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
tom = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
